using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ControllerListener2 : MonoBehaviour
{
    // These were generated by checking the "Generate C# Class" or the input actions component and hitting apply
    private InputXBoxController _input;
    private XRIDefaultInputActions _xr_input;       // not sure if this would be useful

    private void Awake()
    {
        _input = new InputXBoxController();
        _xr_input = new XRIDefaultInputActions();
    }

    private void OnEnable()
    {
        _input.Enable();
        _xr_input.Enable();
    }
    private void OnDisable()
    {
        _input.Disable();
        _xr_input.Disable();
    }

    void Update()
    {
    }
}
